<a href="https://colab.research.google.com/github/arunkumarpallala/intern-iit-hyd/blob/main/working_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv("/content/fold1_train.csv",sep='\t')

In [3]:
df.head(-1)

                                    filename scene_label
0      audio/airport-lisbon-1000-40000-a.wav     airport
1      audio/airport-prague-1015-40019-a.wav     airport
2      audio/airport-prague-1023-40027-a.wav     airport
3      audio/airport-prague-1023-40038-a.wav     airport
4      audio/airport-prague-1034-40041-a.wav     airport
...                                      ...         ...
13956      audio/tram-vienna-200-6049-s3.wav        tram
13957   audio/tram-barcelona-180-5570-s3.wav        tram
13958    audio/tram-helsinki-184-5738-s3.wav        tram
13959    audio/tram-lisbon-1131-43892-s3.wav        tram
13960      audio/tram-london-188-5815-s3.wav        tram

[13961 rows x 2 columns]

In [11]:
no_of_classes =np.unique(df['scene_label'])
no_of_classes

array(['airport', 'bus', 'metro', 'metro_station', 'park',
       'public_square', 'shopping_mall', 'street_pedestrian',
       'street_traffic', 'tram'], dtype=object)

In [16]:
travelling = df[(df['scene_label']=='bus') | (df['scene_label']=='tram')]
travelling

                                   filename scene_label
1393        audio/bus-lyon-1001-40001-a.wav         bus
1394      audio/bus-lisbon-1013-40015-a.wav         bus
1395      audio/bus-prague-1030-40034-a.wav         bus
1396      audio/bus-prague-1032-40036-a.wav         bus
1397        audio/bus-lyon-1001-40044-a.wav         bus
...                                     ...         ...
13957  audio/tram-barcelona-180-5570-s3.wav        tram
13958   audio/tram-helsinki-184-5738-s3.wav        tram
13959   audio/tram-lisbon-1131-43892-s3.wav        tram
13960     audio/tram-london-188-5815-s3.wav        tram
13961     audio/tram-lyon-1112-41171-s3.wav        tram

[2779 rows x 2 columns]

In [17]:
res_area=df[(df['scene_label']=='shopping_mall')]
res_area

                                           filename    scene_label
8411    audio/shopping_mall-lisbon-1002-40002-a.wav  shopping_mall
8412    audio/shopping_mall-prague-1009-40009-a.wav  shopping_mall
8413    audio/shopping_mall-prague-1009-40016-a.wav  shopping_mall
8414    audio/shopping_mall-prague-1031-40035-a.wav  shopping_mall
8415      audio/shopping_mall-lyon-1043-40055-a.wav  shopping_mall
...                                             ...            ...
9779  audio/shopping_mall-barcelona-125-3731-s3.wav  shopping_mall
9780   audio/shopping_mall-helsinki-129-3878-s3.wav  shopping_mall
9781   audio/shopping_mall-lisbon-1125-43904-s3.wav  shopping_mall
9782     audio/shopping_mall-london-131-3925-s3.wav  shopping_mall
9783     audio/shopping_mall-lyon-1043-42036-s3.wav  shopping_mall

[1373 rows x 2 columns]

##2016dataset csv

In [ ]:
import pandas as pd
df=pd.read_csv("/content/meta2016.txt",sep='\t',header=None)
df.head(-1)

                           0                 1
0        audio/a001_0_30.wav  residential_area
1     audio/a001_120_150.wav  residential_area
2     audio/a001_150_180.wav  residential_area
3       audio/a001_30_60.wav  residential_area
4       audio/a001_60_90.wav  residential_area
...                      ...               ...
1164  audio/b116_150_180.wav            office
1165  audio/b116_180_210.wav            office
1166  audio/b116_240_270.wav            office
1167    audio/b116_30_60.wav            office
1168    audio/b116_60_90.wav            office

[1169 rows x 2 columns]

In [ ]:
home = df[(df[1]=='home')]
home.head(-1)

In [ ]:
forest = df[(df[1]=='forest_path')]
forest.head(-1)
forest.to_excel("2016.xlsx",sheet_name='forest')

In [ ]:
residential_area = df[df[1]=='residential_area']
residential_area.head(-1)
residential_area.to_excel("2016.xlsx",sheet_name='residential')

In [ ]:
bus=df[(df[1]=='bus')]
bus.head(-1)
bus.to_excel("2016.xlsx",sheet_name='bus')

In [ ]:
train = df[(df[1]=='train') ]
train.head(-1)
train.to_excel("2016.xlsx",sheet_name='train')

In [ ]:
tram =df[(df[1]=='tram')]
tram.head(-1)
tram.to_excel("2016.xlsx",sheet_name='tram')

In [ ]:
home.to_csv("2016",mode='a',index = False, header=None)
forest.to_csv("2016",mode='a',index = False, header=None)
residential_area.to_csv("2016",mode='a',index = False, header=None)
bus.to_csv("2016",mode='a',index = False, header=None)
train.to_csv("2016",mode='a',index = False, header=None)
tram.to_csv("2016",mode='a',index = False, header=None)

In [ ]:
import os

df1=pd.read_csv("/content/2016",header=None)
df1.head(-1)

                          0     1
0       audio/a030_0_30.wav  home
1    audio/a030_120_150.wav  home
2    audio/a030_150_180.wav  home
3      audio/a030_30_60.wav  home
4      audio/a030_60_90.wav  home
..                      ...   ...
462   audio/b080_90_120.wav  tram
463     audio/b082_0_30.wav  tram
464  audio/b082_120_150.wav  tram
465  audio/b082_150_180.wav  tram
466    audio/b082_60_90.wav  tram

[467 rows x 2 columns]

In [ ]:
import shutil
dir='data2016'
folder='dataset'
des='data2016/collected_data/'

if not os.path.exists(des):
  os.mkdir(des)


for i in range(467):
  file_path=os.path.join(dir,folder,df1.iloc[i][0])
  #print(file_path)
  #file=str(file_path).split('/')[-1]
  #print(file)
  #shutil.copy(file_path,des)